### ISSUE TITLE
Code Inspection Results

### ISSUE THREAD

**Issue by blukat29** [Nova-12/GraphEye#1]
## core
- [x] `Exporter.scala`: 3 boolean parameters without name
## web
- [x] `APIController.java`: 3 unused imports, 1 bad string comparison
- [x] `CoreProcess.java`: 2 unused assignments, 1 empty catch block, 
- [x] `DBClient.java`: 2 unused imports, 1 unused declaration.
- [x] `Job.java`: 2 access modifiers, 6 unused variables and methods, 2 unused imports.

**Comment by wjw0926** [comment]
Gaegood!
